### ISSUE TITLE
Indexed Buffer out of range

### ISSUE THREAD

**Issue by tiby312** [glium/glium#1544]
I'm trying to get opengl es 3.1 compute shaders working on my machine.
I can build the window and build the shader, but it seems the buffer object isnt being bound or something.

Here is my program: 

```rust
#[macro_use]
extern crate glium;
extern crate rand;
use glium::glutin;

fn main() {
    use glium::DisplayBuild;

    let display = glutin::WindowBuilder::new()
        .with_gl(glutin::GlRequest::Specific(glutin::Api::OpenGlEs, (3, 1)))
        .build_glium()
        .unwrap();

    let program = glium::program::ComputeShader::from_source(&display, r#"\
            #version 310 es

            layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
            
            layout(std430) buffer MyBlock {
                float value;
            };

            void main() {
                
            }
        "#).unwrap();


    #[derive(Copy,Clone)]
    struct Data {
        value:f32
    }

    //implement_buffer_content!(Data);
    implement_uniform_block!(Data, value);

    println!("setting num values");


    let mut buffer = glium::uniforms::UniformBuffer::dynamic(&display, Data { value: 0.0f32 }).unwrap();

              
    {
        let mut mapping = buffer.map();
        mapping.value=42.0;
    }

    println!("about to execute program!"); 
    program.execute(uniform! { MyBlock: &*buffer }, 1, 1, 1);
    println!("finished executing");

}
```

Here is my output:

```
setting num values
about to execute program!
thread 'main' panicked at 'Indexed buffer out of range', /home/ken/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.15.0/src/buffer/alloc.rs:1504
stack backtrace:
   1:     0x5631b5db884a - std::sys::imp::backtrace::tracing::imp::write::h944c02ac40aee2d7
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x5631b5dbaecf - std::panicking::default_hook::{{closure}}::h6875a2976258b020
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:247
   3:     0x5631b5dbaace - std::panicking::default_hook::h88ffbc5922643264
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:263
   4:     0x5631b5dbb317 - std::panicking::rust_panic_with_hook::ha5aed1dfc0e220e3
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:451
   5:     0x5631b5d26f6f - std::panicking::begin_panic::h5f0a1fd8f4de57ec
   6:     0x5631b5d2e915 - glium::buffer::alloc::indexed_bind_buffer::hb1721a8eb0433b21
   7:     0x5631b5d2cb81 - glium::buffer::alloc::Alloc::prepare_and_bind_for_shared_storage::h5000a4a119149e32
   8:     0x5631b5d1a7f6 - glium::uniforms::bind::<impl glium::UniformsExt for U>::bind_uniforms::{{closure}}::ha37e55aef4003d76
   9:     0x5631b5d1dd61 - kdtree::main::h46ec7e9319673e56
  10:     0x5631b5dc3d4a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  11:     0x5631b5dbbb5a - std::rt::lang_start::h5d71a3afaaa4b2ff
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/rt.rs:57
  12:     0x7f75333fc82f - __libc_start_main
  13:     0x5631b5d155f8 - _start
  14:                0x0 - <unknown>

```

Here is what's on my machine
```
ken@ken-E403SA:~/ken/kdtree$ glxinfo | grep "OpenGL"
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics (Cherryview) 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 11.2.0
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 11.2.0
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 11.2.0
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:

```

Any help appreciated!

**Comment by tomaka** [comment]
It looks like your hardware doesn't support SSBOs. The weird thing is that this should be caught by the driver when the shader is compiled, not when it is executed.

**Comment by tiby312** [comment]
Thanks. Yes I figured that since it let me compile the shader, it must support them, but I guess not haha. Oh well.

**Comment by avl** [comment]
Maybe this could be closed, as it'd presumably a driver-bug? Any program using SSBO's that stìll knows how to function when they are not available might be advanced enough that we simply say it'll have to implement its own feature detection workarounds on buggy drivers (but please create a PR if you solve this? :-) )
