### ISSUE TITLE
Tests failures

### ISSUE THREAD

**Issue by eclipseo** [glium/glium#1710]
Rust 1.29 + glium = "0.22.0"

```
/usr/bin/cargo test -j2 --release --no-fail-fast

failures:

---- src/lib.rs -  (line 12) stdout ----
error[E0061]: this function takes 1 parameter but 2 parameters were supplied
 --> src/lib.rs:20:10
  |
9 |         .with_dimensions(1024, 768)
  |          ^^^^^^^^^^^^^^^ expected 1 parameter

thread 'src/lib.rs -  (line 12)' panicked at 'couldn't compile the test', librustdoc/test.rs:332:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- src/uniforms/buffer.rs - uniforms::buffer::UniformBuffer (line 16) stdout ----
error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found `MyBlock`
 --> src/uniforms/buffer.rs:17:9
  |
3 | uniform MyBlock {
  |         ^^^^^^^ expected one of 8 possible tokens here

error[E0425]: cannot find value `uniform` in this scope
 --> src/uniforms/buffer.rs:17:1
  |
3 | uniform MyBlock {
  | ^^^^^^^ not found in this scope

thread 'src/uniforms/buffer.rs - uniforms::buffer::UniformBuffer (line 16)' panicked at 'couldn't compile the test', librustdoc/test.rs:332:13

---- src/uniforms/buffer.rs - uniforms::buffer::UniformBuffer (line 22) stdout ----
error: cannot find macro `uniform!` in this scope
 --> src/uniforms/buffer.rs:23:1
  |
3 | uniform! {
  | ^^^^^^^

thread 'src/uniforms/buffer.rs - uniforms::buffer::UniformBuffer (line 22)' panicked at 'couldn't compile the test', librustdoc/test.rs:332:13

---- src/vertex/buffer.rs - vertex::buffer::VertexBuffer<T>::new_raw (line 238) stdout ----
error[E0271]: type mismatch resolving `<[(std::borrow::Cow<'static, str>, usize, glium::vertex::AttributeType, bool)] as std::borrow::ToOwned>::Owned == std::vec::Vec<(std::borrow::Cow<'_, str>, usize, glium::vertex::AttributeType)>`
  --> src/vertex/buffer.rs:244:16
   |
7  |   let bindings = Cow::Owned(vec![(
   |  ________________^
8  | |         Cow::Borrowed("position"), 0,
9  | |         glium::vertex::AttributeType::F32F32,
10 | |     ), (
...  |
13 | |     ),
14 | | ]);
   | |__^ expected a tuple with 4 elements, found one with 3 elements
   |
   = note: expected type `std::vec::Vec<(std::borrow::Cow<'static, str>, usize, glium::vertex::AttributeType, bool)>`
              found type `std::vec::Vec<(std::borrow::Cow<'_, str>, usize, glium::vertex::AttributeType)>`

thread 'src/vertex/buffer.rs - vertex::buffer::VertexBuffer<T>::new_raw (line 238)' panicked at 'couldn't compile the test', librustdoc/test.rs:332:13


failures:
    src/lib.rs -  (line 12)
    src/uniforms/buffer.rs - uniforms::buffer::UniformBuffer (line 16)
    src/uniforms/buffer.rs - uniforms::buffer::UniformBuffer (line 22)
    src/vertex/buffer.rs - vertex::buffer::VertexBuffer<T>::new_raw (line 238)

test result: FAILED. 101 passed; 4 failed; 2 ignored; 0 measured; 0 filtered out
```

**Comment by est31** [comment]
Should be fixed now, not sure which PR it was. If there are still problems, please point them out!
