### ISSUE TITLE
fullscreen example fails

### ISSUE THREAD

**Issue by vadixidav** [glium/glium#1722]
I am currently on Windows 10 while testing this out. The `fullscreen` example fails (in `0.23.0` and `master`). Note that version `0.22.0` did not have this bug. The reported error references a method that was removed. See below for the command and backtrace.

```rust
$ RUST_BACKTRACE=1 cargo run --example fullscreen
Finished dev [unoptimized + debuginfo] target(s) in 0.24s
Running `target\debug\examples\fullscreen.exe`
Press Enter to switch fullscreen mode
thread 'main' panicked at 'Context sharing is not allowed when using `new()`. Please instead use `new_shared()`.', C:\Users\vax\.cargo\registry\src\github.com-1ecc6299db9ec 823\glutin-0.19.0\src\lib.rs:365:51
stack backtrace:
0: std::sys::windows::backtrace::set_frames
at /rustc/4c2be9c97fb60a01c545b8e8fa61e4247ae5c9b2\/src\libstd\sys\windows\backtrace\mod.rs:94
1: std::sys::windows::backtrace::unwind_backtrace
at /rustc/4c2be9c97fb60a01c545b8e8fa61e4247ae5c9b2\/src\libstd\sys\windows\backtrace\mod.rs:81
2: std::sys_common::backtrace::_print
at /rustc/4c2be9c97fb60a01c545b8e8fa61e4247ae5c9b2\/src\libstd\sys_common\backtrace.rs:70
3: std::sys_common::backtrace::print
at /rustc/4c2be9c97fb60a01c545b8e8fa61e4247ae5c9b2\/src\libstd\sys_common\backtrace.rs:58
4: std::panicking::default_hook::{{closure}}
at /rustc/4c2be9c97fb60a01c545b8e8fa61e4247ae5c9b2\/src\libstd\panicking.rs:200
5: std::panicking::default_hook
at /rustc/4c2be9c97fb60a01c545b8e8fa61e4247ae5c9b2\/src\libstd\panicking.rs:215
6: std::panicking::rust_panic_with_hook
at /rustc/4c2be9c97fb60a01c545b8e8fa61e4247ae5c9b2\/src\libstd\panicking.rs:478
7: std::panicking::begin_panic
at /rustc/4c2be9c97fb60a01c545b8e8fa61e4247ae5c9b2\src\libstd\panicking.rs:412
8: glutin::{{impl}}::new::{{closure}}
at C:\Users\vax\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.19.0\src\lib.rs:365
9: core::option::Option::map                                                                          at /rustc
/4c2be9c97fb60a01c545b8e8fa61e4247ae5c9b2\src\libcore\option.rs:414
10: glutin::GlAttributes::map_sharing                                                                  at C:\Users\vax\.cargo
\registry\src\github.com-1ecc6299db9ec823\glutin-0.19.0\src\lib.rs:926
11: glutin::GlWindow::new
at C:\Users\vax\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.19.0\src\lib.rs:365
12: glium::backend::glutin::Display::rebuild
at .\src\backend\glutin\mod.rs:138
13: fullscreen::main::{{closure}}
at .\examples\fullscreen.rs:131
14: fullscreen::support::start_loop
at .\examples\support\mod.rs:23
15: fullscreen::main
at .\examples\fullscreen.rs:83
16: std::rt::lang_start::{{closure}}<()>
at /rustc/4c2be9c97fb60a01c545b8e8fa61e4247ae5c9b2\src\libstd\rt.rs:64
17: std::rt::lang_start_internal::{{closure}}
at /rustc/4c2be9c97fb60a01c545b8e8fa61e4247ae5c9b2\/src\libstd\rt.rs:49
18: std::panicking::try::do_call
at /rustc/4c2be9c97fb60a01c545b8e8fa61e4247ae5c9b2\/src\libstd\panicking.rs:297
19: panic_unwind::__rust_maybe_catch_panic
at /rustc/4c2be9c97fb60a01c545b8e8fa61e4247ae5c9b2\/src\libpanic_unwind\lib.rs:92
20: std::panicking::try
at /rustc/4c2be9c97fb60a01c545b8e8fa61e4247ae5c9b2\/src\libstd\panicking.rs:276
21: std::panic::catch_unwind
at /rustc/4c2be9c97fb60a01c545b8e8fa61e4247ae5c9b2\/src\libstd\panic.rs:388
22: std::rt::lang_start_internal
at /rustc/4c2be9c97fb60a01c545b8e8fa61e4247ae5c9b2\/src\libstd\rt.rs:48
23: std::rt::lang_start<()>
at /rustc/4c2be9c97fb60a01c545b8e8fa61e4247ae5c9b2\src\libstd\rt.rs:64
24: main
25: invoke_main
at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
26: __scrt_common_main_seh
at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
27: BaseThreadInitThunk
28: RtlUserThreadStart
error: process didn't exit successfully: `target\debug\examples\fullscreen.exe` (exit code: 101)
--
```

**Comment by seivan** [comment]
This seems to be an issue with Glutin.
