### ISSUE TITLE
Panic at example "Tessellation"

### ISSUE THREAD

**Issue by PonasKovas** [glium/glium#1813]
OS: Arch Linux,

When I try to run the "tessellation" example, I get an error:
```
> RUST_BACKTRACE=full cargo run --example tessellation
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PrimitiveTypeNotSupported', src/libcore/result.rs:1188:5
stack backtrace:
   0:     0x5626758bad14 - backtrace::backtrace::libunwind::trace::h257ee8fa702033a5
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x5626758bad14 - backtrace::backtrace::trace_unsynchronized::h5f0627dd9ccaab6f
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x5626758bad14 - std::sys_common::backtrace::_print_fmt::h4ed17834c4e5b6fe
                               at src/libstd/sys_common/backtrace.rs:84
   3:     0x5626758bad14 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h68dbadc0bcc77b5f
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x5626758db3dc - core::fmt::write::hc38fdda30204d4dc
                               at src/libcore/fmt/mod.rs:1025
   5:     0x5626758b8257 - std::io::Write::write_fmt::h0900d6e763137782
                               at src/libstd/io/mod.rs:1426
   6:     0x5626758bce8e - std::sys_common::backtrace::_print::h03ca3de8c1fabc8b
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x5626758bce8e - std::sys_common::backtrace::print::h0089c2a21e41632b
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x5626758bce8e - std::panicking::default_hook::{{closure}}::he2d2ff837d4de97e
                               at src/libstd/panicking.rs:193
   9:     0x5626758bcb81 - std::panicking::default_hook::h2f717321fdee40b4
                               at src/libstd/panicking.rs:210
  10:     0x5626758bd56b - std::panicking::rust_panic_with_hook::h9d80a6967ad27edd
                               at src/libstd/panicking.rs:471
  11:     0x5626758bd11e - rust_begin_unwind
                               at src/libstd/panicking.rs:375
  12:     0x5626758d837e - core::panicking::panic_fmt::h15ac915805b55762
                               at src/libcore/panicking.rs:84
  13:     0x5626758d8477 - core::result::unwrap_failed::h7ee63907f56ec7cf
                               at src/libcore/result.rs:1188
  14:     0x5626753bb67e - core::result::Result<T,E>::unwrap::h55392374f0c4069b
                               at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libcore/result.rs:956
  15:     0x562675385a8d - tessellation::main::h1bcdf082531164f8
                               at examples/tessellation.rs:36
  16:     0x562675391ac0 - std::rt::lang_start::{{closure}}::h2a7640b3fb2e3571
                               at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/rt.rs:67
  17:     0x5626758bcfb3 - std::rt::lang_start_internal::{{closure}}::hc3a7bf6141d6fb71
                               at src/libstd/rt.rs:52
  18:     0x5626758bcfb3 - std::panicking::try::do_call::h1f3e9b1e5088796f
                               at src/libstd/panicking.rs:292
  19:     0x5626758c0e4a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  20:     0x5626758bda00 - std::panicking::try::h9241957305334fb5
                               at src/libstd/panicking.rs:270
  21:     0x5626758bda00 - std::panic::catch_unwind::h6f26ed7457a3b67e
                               at src/libstd/panic.rs:394
  22:     0x5626758bda00 - std::rt::lang_start_internal::hf225ee90fc1b21bb
                               at src/libstd/rt.rs:51
  23:     0x562675391a99 - std::rt::lang_start::h22775773f9fdd6ab
                               at /rustc/0de96d37fbcc54978458c18f5067cd9817669bc8/src/libstd/rt.rs:67
  24:     0x56267538614a - main
  25:     0x7fc52a3f8153 - __libc_start_main
  26:     0x5626752d41ae - _start
  27:                0x0 - <unknown>
```

**Comment by spearman** [comment]
Tessellation stages are only supported in OpenGL 4.0+, check your driver version and hardware compatibility.
