### ISSUE TITLE
gl function was not loaded

### ISSUE THREAD

**Issue by virtualritz** [glium/glium#1840]
I'm seeing [this issue](https://github.com/glium/glium/issues/1648) with glium 0.27.0 on macOS 10.15.4 on a 2014 MBP with Intel Iris GPU.
```
thread 'main' panicked at 'gl function was not loaded', /Users/moritz/code/generative/target/release/build/glium-5a230c4287d7cff8/out/gl_bindings.rs:2535:13
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic
   7: glium::gl::missing_fn_panic
   8: glium::texture::any::new_texture
   9: valora::gpu::Gpu::build_texture
  10: valora::run_fn
  11: generative::main
  12: std::rt::lang_start::{{closure}}
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
  15: std::rt::lang_start_internal
  16: main
```

**Comment by chengluyu** [comment]
Me, too. I was also trying [valora](https://paytonturnage.gitbook.io/valora/) and met this error on macOS 10.15.4

**Comment by est31** [comment]
I don't have a Mac computer. I wonder how a minimal reproducing example could look like.

**Comment by virtualritz** [comment]
I'm using this example from the `valora` guide:
```Rust
use valora::prelude::*;

fn main() -> Result<()> {
    run_fn(Options::from_args(), |_gpu, world, _rng| {
        Ok(move |ctx: Context, canvas: &mut Canvas| {
            canvas.set_color(LinSrgb::new(1., 1., 1.));
            canvas.paint(Filled(ctx.world));

            let max_radius = world.width / 3.;
            let radius =
                ctx.time.as_secs_f32().cos().abs() * max_radius;

            canvas.set_color(LinSrgb::new(1., 0., 0.));
            canvas
                .paint(Filled(Ellipse::circle(world.center(), radius)));
        })
    })
}
```

**Comment by est31** [comment]
Can you reproduce it only with glium's API? And on other operating systems than Mac?

**Comment by jarhill0** [comment]
> And on other operating systems than Mac?

As someone else who has experienced this panic, I think it's a macOS-specific issue.

**Comment by mlakewood** [comment]
I have tracked down where the issue is and have opened a PR to demonstrate the really bad and terrible fix -> https://github.com/glium/glium/pull/1846

Hopefully somebody who knows more can make a better fix.

**Comment by wbrickner** [comment]
@mlakewood your fork does not solve this issue unfortunately, I am experiencing it after replacing `valora`'s dependency on `glium` with your fork.  I am running `macOS v11.1 Big Sur`.

My full backtrace (ignore `valora` specifics):

```
thread 'main' panicked at 'gl function was not loaded', /Users/wbrickner/Work/ExotechModern/em-studio/studio/target/debug/build/glium-41036f0d5f843c01/out/gl_bindings.rs:2535:13
stack backtrace:
   0:        0x102ada13c - std::backtrace_rs::backtrace::libunwind::trace::hd4e4f36eb9f0f866
                               at /rustc/44e3daf5eee8263dfc3a2509e78ddd1f6f783a0e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x102ada13c - std::backtrace_rs::backtrace::trace_unsynchronized::h713e8299cd20066f
                               at /rustc/44e3daf5eee8263dfc3a2509e78ddd1f6f783a0e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x102ada13c - std::sys_common::backtrace::_print_fmt::h10db128357fb183a
                               at /rustc/44e3daf5eee8263dfc3a2509e78ddd1f6f783a0e/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x102ada13c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha6f5ddd5259d3e16
                               at /rustc/44e3daf5eee8263dfc3a2509e78ddd1f6f783a0e/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x102af486d - core::fmt::write::hefe95a44532fe6ed
                               at /rustc/44e3daf5eee8263dfc3a2509e78ddd1f6f783a0e/library/core/src/fmt/mod.rs:1078:17
   5:        0x102ad6fe6 - std::io::Write::write_fmt::hf513c99961415bff
                               at /rustc/44e3daf5eee8263dfc3a2509e78ddd1f6f783a0e/library/std/src/io/mod.rs:1519:15
   6:        0x102adc089 - std::sys_common::backtrace::_print::he8e57200c2a0a691
                               at /rustc/44e3daf5eee8263dfc3a2509e78ddd1f6f783a0e/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x102adc089 - std::sys_common::backtrace::print::hab21ea437dd3480e
                               at /rustc/44e3daf5eee8263dfc3a2509e78ddd1f6f783a0e/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x102adc089 - std::panicking::default_hook::{{closure}}::h70a3a940826edea5
                               at /rustc/44e3daf5eee8263dfc3a2509e78ddd1f6f783a0e/library/std/src/panicking.rs:208:50
   9:        0x102adbc19 - std::panicking::default_hook::h9520f36dd50be056
                               at /rustc/44e3daf5eee8263dfc3a2509e78ddd1f6f783a0e/library/std/src/panicking.rs:225:9
  10:        0x102adc70b - std::panicking::rust_panic_with_hook::h102f8bee4e0ef4c7
                               at /rustc/44e3daf5eee8263dfc3a2509e78ddd1f6f783a0e/library/std/src/panicking.rs:591:17
  11:        0x1029d0897 - std::panicking::begin_panic::{{closure}}::he976d24348cdb14b
                               at /Users/wbrickner/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:520:9
  12:        0x1029d14c8 - std::sys_common::backtrace::__rust_end_short_backtrace::haa1528051c10e5b0
                               at /Users/wbrickner/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x102aff037 - std::panicking::begin_panic::hc10b22d30b6249b0
                               at /Users/wbrickner/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:519:12
  14:        0x10293389c - glium::gl::missing_fn_panic::hf2e749dd1b57a8e9
                               at /Users/wbrickner/Work/ExotechModern/em-studio/studio/target/debug/build/glium-41036f0d5f843c01/out/gl_bindings.rs:2535:13
  15:        0x102573d65 - glium::gl::Gl::TexStorage2DMultisample::hef8dd46552c388f4
                               at /Users/wbrickner/Work/ExotechModern/em-studio/studio/target/debug/build/glium-41036f0d5f843c01/out/gl_bindings.rs:8320:242
  16:        0x10258e11e - glium::texture::any::new_texture::hc8079412e58f82dc
                               at /Users/wbrickner/Work/ExotechModern/em-studio/custom-deps/glium/src/texture/any.rs:367:17
  17:        0x10258b859 - glium::texture::texture2d_multisample::Texture2dMultisample::empty_with_format::h2ed72f56c8cc4683
                               at /Users/wbrickner/Work/ExotechModern/em-studio/studio/target/debug/build/glium-41036f0d5f843c01/out/textures.rs:6424:9
  18:        0x102594603 - valora::gpu::Gpu::build_texture::h3bbc174cd521eff0
                               at /Users/wbrickner/Work/ExotechModern/em-studio/custom-deps/valora/src/gpu.rs:245:12
  19:        0x1024ac0ca - valora::run_fn::h1c5009fe54539a9a
                               at /Users/wbrickner/Work/ExotechModern/em-studio/custom-deps/valora/src/lib.rs:237:22
  20:        0x1024856da - studio::main::h2a23893835d88c10
                               at /Users/wbrickner/Work/ExotechModern/em-studio/studio/src/main.rs:4:5
  21:        0x102481f7e - core::ops::function::FnOnce::call_once::h793dacac361e2402
                               at /Users/wbrickner/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  22:        0x10247f1c1 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4e5e51da33bc0932
                               at /Users/wbrickner/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  23:        0x10249af04 - std::rt::lang_start::{{closure}}::h83a1198b2f685535
                               at /Users/wbrickner/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:66:18
  24:        0x102adcb64 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h4ab201f754b12ec0
                               at /rustc/44e3daf5eee8263dfc3a2509e78ddd1f6f783a0e/library/core/src/ops/function.rs:259:13
  25:        0x102adcb64 - std::panicking::try::do_call::h2d40bab4a9c2dc4b
                               at /rustc/44e3daf5eee8263dfc3a2509e78ddd1f6f783a0e/library/std/src/panicking.rs:379:40
  26:        0x102adcb64 - std::panicking::try::hedf52334a975e681
                               at /rustc/44e3daf5eee8263dfc3a2509e78ddd1f6f783a0e/library/std/src/panicking.rs:343:19
  27:        0x102adcb64 - std::panic::catch_unwind::hb38d8390232c8f25
                               at /rustc/44e3daf5eee8263dfc3a2509e78ddd1f6f783a0e/library/std/src/panic.rs:396:14
  28:        0x102adcb64 - std::rt::lang_start_internal::hebea83fb59fe572e
                               at /rustc/44e3daf5eee8263dfc3a2509e78ddd1f6f783a0e/library/std/src/rt.rs:51:25
  29:        0x10249aee1 - std::rt::lang_start::h45147dbbf24d5598
                               at /Users/wbrickner/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:65:5
  30:        0x102485712 - _main
```

I *suspect* that the problem originates in the build scripts associated with `glium`, which as I understand dynamically generate rust bindings to OpenGL.  I think the scripts generate `gl_bindings.rs` and `textures.rs`. They're quite large so I've uploaded them instead of providing them inline.  

On my machine, they are generated as:
- [gl_bindings.rs.zip](https://github.com/glium/glium/files/5832432/gl_bindings.rs.zip)
- [textures.rs.zip](https://github.com/glium/glium/files/5832433/textures.rs.zip)

Hopefully this helps in resolving this issue.

**Comment by wbrickner** [comment]
If it is helpful, the output of `cargo test` in the `glium` repo on my machine yields:

```
running 11 tests
test macros::tests::assert_no_error_macro ... ok
test macros::tests::trailing_comma_impl_uniforms ... ok
test macros::tests::trailing_comma_impl_vertex ... ok
test utils::bitsfield::tests::get_unused ... ok
test texture::bindless::test::texture_handle_size ... ok
test utils::bitsfield::tests::get_unused2 ... ok
test utils::bitsfield::tests::is_used ... ok
test version::tests::valid_gl_versions ... ok
test version::tests::invalid_gl_version ... ok
test version::tests::invalid_gles_version ... ok
test version::tests::valid_gles_versions ... ok

test result: ok. 11 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running target/debug/deps/attrs-0f2236ce673b0783

running 51 tests
test attribute_float_u16 ... FAILED
test attribute_float_i32 ... FAILED
test attribute_float_f32 ... FAILED
test attribute_float_u32 ... FAILED
test attribute_float_i16 ... FAILED
test attribute_float_i8 ... FAILED
test attribute_float_u8 ... FAILED
test attribute_types_mismatch ... FAILED
test attribute_vec2_f32 ... FAILED
test attribute_vec2_i16 ... FAILED
test attribute_vec2_i32 ... FAILED
test attribute_vec2_i8 ... FAILED
test attribute_vec2_tuple_f32 ... FAILED
test attribute_vec2_tuple_i16 ... FAILED
test attribute_vec2_tuple_i32 ... FAILED
test attribute_vec2_tuple_i8 ... FAILED
test attribute_vec2_tuple_u16 ... FAILED
test attribute_vec2_tuple_u32 ... FAILED
test attribute_vec2_tuple_u8 ... FAILED
test attribute_vec2_u16 ... FAILED
test attribute_vec2_u32 ... FAILED
test attribute_vec2_u8 ... FAILED
test attribute_vec3_f32 ... FAILED
test attribute_vec3_i16 ... FAILED
test attribute_vec3_i32 ... FAILED
test attribute_vec3_i8 ... FAILED
test attribute_vec3_tuple_f32 ... FAILED
test attribute_vec3_tuple_i16 ... FAILED
test attribute_vec3_tuple_i32 ... FAILED
test attribute_vec3_tuple_i8 ... FAILED
test attribute_vec3_tuple_u16 ... FAILED
test attribute_vec3_tuple_u32 ... FAILED
test attribute_vec3_tuple_u8 ... FAILED
test attribute_vec3_u16 ... FAILED
test attribute_vec3_u32 ... FAILED
test attribute_vec3_u8 ... FAILED
test attribute_vec4_f32 ... FAILED
test attribute_vec4_i16 ... FAILED
test attribute_vec4_i32 ... FAILED
test attribute_vec4_i8 ... FAILED
test attribute_vec4_tuple_f32 ... FAILED
test attribute_vec4_tuple_i16 ... FAILED
test attribute_vec4_tuple_i32 ... FAILED
test attribute_vec4_tuple_i8 ... FAILED
test attribute_vec4_tuple_u16 ... FAILED
test attribute_vec4_tuple_u32 ... FAILED
test attribute_vec4_tuple_u8 ... FAILED
test attribute_vec4_u16 ... FAILED
test attribute_vec4_u32 ... FAILED
test attribute_vec4_u8 ... FAILED
test missing_attribute ... FAILED

failures:

---- attribute_float_u16 stdout ----
thread 'attribute_float_u16' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_float_i32 stdout ----
thread 'attribute_float_i32' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_float_f32 stdout ----
thread 'attribute_float_f32' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_float_u32 stdout ----
thread 'attribute_float_u32' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- attribute_float_i16 stdout ----
thread 'attribute_float_i16' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_float_i8 stdout ----
thread 'attribute_float_i8' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_float_u8 stdout ----
thread 'attribute_float_u8' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_types_mismatch stdout ----
thread 'attribute_types_mismatch' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17
note: panic did not contain expected string
      panic message: `"On macOS, `EventLoop` must be created on the main thread!"`,
 expected substring: `"The program attribute `field1` does not match the vertex format"`
---- attribute_vec2_f32 stdout ----
thread 'attribute_vec2_f32' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec2_i16 stdout ----
thread 'attribute_vec2_i16' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec2_i32 stdout ----
thread 'attribute_vec2_i32' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec2_i8 stdout ----
thread 'attribute_vec2_i8' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec2_tuple_f32 stdout ----
thread 'attribute_vec2_tuple_f32' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec2_tuple_i16 stdout ----
thread 'attribute_vec2_tuple_i16' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec2_tuple_i32 stdout ----
thread 'attribute_vec2_tuple_i32' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec2_tuple_i8 stdout ----
thread 'attribute_vec2_tuple_i8' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec2_tuple_u16 stdout ----
thread 'attribute_vec2_tuple_u16' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec2_tuple_u32 stdout ----
thread 'attribute_vec2_tuple_u32' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec2_tuple_u8 stdout ----
thread 'attribute_vec2_tuple_u8' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec2_u16 stdout ----
thread 'attribute_vec2_u16' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec2_u32 stdout ----
thread 'attribute_vec2_u32' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec2_u8 stdout ----
thread 'attribute_vec2_u8' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec3_f32 stdout ----
thread 'attribute_vec3_f32' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec3_i16 stdout ----
thread 'attribute_vec3_i16' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec3_i32 stdout ----
thread 'attribute_vec3_i32' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec3_i8 stdout ----
thread 'attribute_vec3_i8' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec3_tuple_f32 stdout ----
thread 'attribute_vec3_tuple_f32' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec3_tuple_i16 stdout ----
thread 'attribute_vec3_tuple_i16' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec3_tuple_i32 stdout ----
thread 'attribute_vec3_tuple_i32' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec3_tuple_i8 stdout ----
thread 'attribute_vec3_tuple_i8' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec3_tuple_u16 stdout ----
thread 'attribute_vec3_tuple_u16' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec3_tuple_u32 stdout ----
thread 'attribute_vec3_tuple_u32' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec3_tuple_u8 stdout ----
thread 'attribute_vec3_tuple_u8' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec3_u16 stdout ----
thread 'attribute_vec3_u16' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec3_u32 stdout ----
thread 'attribute_vec3_u32' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec3_u8 stdout ----
thread 'attribute_vec3_u8' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec4_f32 stdout ----
thread 'attribute_vec4_f32' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec4_i16 stdout ----
thread 'attribute_vec4_i16' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec4_i32 stdout ----
thread 'attribute_vec4_i32' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec4_i8 stdout ----
thread 'attribute_vec4_i8' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec4_tuple_f32 stdout ----
thread 'attribute_vec4_tuple_f32' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec4_tuple_i16 stdout ----
thread 'attribute_vec4_tuple_i16' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec4_tuple_i32 stdout ----
thread 'attribute_vec4_tuple_i32' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec4_tuple_i8 stdout ----
thread 'attribute_vec4_tuple_i8' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec4_tuple_u16 stdout ----
thread 'attribute_vec4_tuple_u16' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec4_tuple_u32 stdout ----
thread 'attribute_vec4_tuple_u32' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec4_tuple_u8 stdout ----
thread 'attribute_vec4_tuple_u8' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec4_u16 stdout ----
thread 'attribute_vec4_u16' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec4_u32 stdout ----
thread 'attribute_vec4_u32' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- attribute_vec4_u8 stdout ----
thread 'attribute_vec4_u8' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17

---- missing_attribute stdout ----
thread 'missing_attribute' panicked at 'On macOS, `EventLoop` must be created on the main thread!', /Users/wbrickner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:46:17
note: panic did not contain expected string
      panic message: `"On macOS, `EventLoop` must be created on the main thread!"`,
 expected substring: `"The program attribute `field2` is missing in the vertex bindings"`

failures:
    attribute_float_f32
    attribute_float_i16
    attribute_float_i32
    attribute_float_i8
    attribute_float_u16
    attribute_float_u32
    attribute_float_u8
    attribute_types_mismatch
    attribute_vec2_f32
    attribute_vec2_i16
    attribute_vec2_i32
    attribute_vec2_i8
    attribute_vec2_tuple_f32
    attribute_vec2_tuple_i16
    attribute_vec2_tuple_i32
    attribute_vec2_tuple_i8
    attribute_vec2_tuple_u16
    attribute_vec2_tuple_u32
    attribute_vec2_tuple_u8
    attribute_vec2_u16
    attribute_vec2_u32
    attribute_vec2_u8
    attribute_vec3_f32
    attribute_vec3_i16
    attribute_vec3_i32
    attribute_vec3_i8
    attribute_vec3_tuple_f32
    attribute_vec3_tuple_i16
    attribute_vec3_tuple_i32
    attribute_vec3_tuple_i8
    attribute_vec3_tuple_u16
    attribute_vec3_tuple_u32
    attribute_vec3_tuple_u8
    attribute_vec3_u16
    attribute_vec3_u32
    attribute_vec3_u8
    attribute_vec4_f32
    attribute_vec4_i16
    attribute_vec4_i32
    attribute_vec4_i8
    attribute_vec4_tuple_f32
    attribute_vec4_tuple_i16
    attribute_vec4_tuple_i32
    attribute_vec4_tuple_i8
    attribute_vec4_tuple_u16
    attribute_vec4_tuple_u32
    attribute_vec4_tuple_u8
    attribute_vec4_u16
    attribute_vec4_u32
    attribute_vec4_u8
    missing_attribute

test result: FAILED. 0 passed; 51 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

**Comment by camdencheek** [comment]
I get a backtrace that points me to `Texture2dMultisample`. 

<detail>

```
❯ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/art`
thread 'main' panicked at 'gl function was not loaded', /Users/ccheek/src/art/target/debug/build/glium-9844ba6034db8cf9/out/gl_bindings.rs:2535:13
stack backtrace:
   0: std::panicking::begin_panic
             at /Users/ccheek/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:519:12
   1: glium::gl::missing_fn_panic
             at ./target/debug/build/glium-9844ba6034db8cf9/out/gl_bindings.rs:2535:13
   2: glium::gl::Gl::TexStorage2DMultisample
             at ./target/debug/build/glium-9844ba6034db8cf9/out/gl_bindings.rs:8320:242
   3: glium::texture::any::new_texture
             at /Users/ccheek/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.27.0/src/texture/any.rs:367:17
   4: glium::texture::texture2d_multisample::Texture2dMultisample::empty_with_format
             at ./target/debug/build/glium-9844ba6034db8cf9/out/textures.rs:6424:9
   5: valora::gpu::Gpu::build_texture
             at /Users/ccheek/.cargo/registry/src/github.com-1ecc6299db9ec823/valora-0.2.12/src/gpu.rs:245:12
   6: valora::run_fn
             at /Users/ccheek/.cargo/registry/src/github.com-1ecc6299db9ec823/valora-0.2.12/src/lib.rs:237:22
   7: art::main
             at ./src/main.rs:4:5
   8: core::ops::function::FnOnce::call_once
             at /Users/ccheek/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</detail>

Based on a similar issue [here](https://github.com/MauriceGit/Voronoi_Image_Manipulation/issues/1), it seems this might be because MacOS uses an older version of OpenGL that does not have that function (I verified that the function does not exist in the header files on my system). Apparently, the `Multisample` variants were only added in OpenGL 4.3, and macOS is currently on OpenGL 4.1.
