### ISSUE TITLE
glium has triggered an OpenGL error during initialization. Please report this error

### ISSUE THREAD

**Issue by theunkn0wn1** [glium/glium#1911]
I probably botched something in the cross-compile, but the error output asked me to submit this anyways.

full error log (generated with `script`)
```
Script started on 2021-02-04 09:54:23+00:00 [TERM="screen.xterm-256color" TTY="/dev/pts/1" COLUMNS="80" LINES="24"]
^[[01;32mpi@sensorpi^[[00m:^[[01;34m~ $^[[00m exit^H^H^H^H./cv-experiments ^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^[[1@R^[[1@U^[[1@S^[[1@T^[[1@_^[[1@B^[[1@A^[[1@C^[[1@K^[[1@T^[[1@R$
Current format:
width      : 1024
height     : 768
pixfmt     : Rgb(24)
stride     : 3072

New format:
width      : 1024
height     : 768
pixfmt     : Rgb(24)
stride     : 3072

glium has triggered an OpenGL error during initialization. Please report this error: https://github.com/glium/glium/issues
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationError("0:2(10): error: GLSL 1.40 is not supported. Supported versions are: 1.10, 1.20, 1.00 $
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::unwrap
             at /rust/lib/rustlib/src/rust/library/core/src/result.rs:973:23
   4: cv_experiments::main
             at /project/src/main.rs:137:9
   5: core::ops::function::FnOnce::call_once
             at /rust/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
^[[01;32mpi@sensorpi^[[00m:^[[01;34m~ $^[[00m exit
exit

Script done on 2021-02-04 09:54:41+00:00 [COMMAND_EXIT_CODE="101"]


```

# Environment
Target: Raspberry Pi model 4b (4gb)
Cross-compiling from Ubuntu 1804 via a rust `cross` container

**Comment by theunkn0wn1** [comment]
Quick update: Bit the bullet and did a build directly on the target Pi, the error persists so its not a cross-build issue.

**Comment by est31** [comment]
It says `GLSL 1.40 is not supported`. I think this is an user error and not a bug with glium. Try lowering the glsl version of your shaders.

**Comment by theunkn0wn1** [comment]
Lowering the shader version also doesn't work, because the shader evidently isn't compatible with the most recent supported version (1.2.0).

**Comment by est31** [comment]
@theunkn0wn1 that's on you or the driver, but not on glium. The message is wrong. Maybe one should change it.
