### ISSUE TITLE
Test atomic_counter/basic Failing

### ISSUE THREAD

**Issue by What42Pizza** [glium/glium#2112]
I wanted to see if I could mess around with this crate, but the test in atomic_counter is failing.

This is the output of running `cargo test +1.76.0 --test atomic_counter`:
```
running 1 test
test basic ... FAILED

failures:

---- basic stdout ----
thread 'basic' panicked at src\buffer\alloc.rs:1528:5:
Indexed buffer out of range
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    basic

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.29s
```

If there's more information that's needed, please let me know

**Comment by What42Pizza** [comment]
Actually I just ran the other test files manually and I found one other failing test, texture_creation/bindless_texture_residency_context_rebuild

**Comment by What42Pizza** [comment]
Okay I see now that the atomic_counter test is a known bug, but I haven't really seen anything about the second test

**Comment by justincredible** [comment]
> Okay I see now that the atomic_counter test is a known bug

This is certainly a problem with Win10 (I haven't tried on Win11); if you're unlucky it can pass sometimes. Never seen it fail on Linuxes.

> one other failing test: texture_creation/bindless_texture_residency_context_rebuild

This one's a lot simpler: [`rebuild_display`](https://github.com/glium/glium/blob/master/tests/support/mod.rs#L219) needs to be re-implemented for `glutin` > 0.29.1.

These [workarounds](https://github.com/justincredible/glium/commit/2708e64) are sufficient for running all tests on Win10.

**Comment by What42Pizza** [comment]
Okay nice, and is this being updated to winit 0.30? That's what I wanted to mess around with, because I wanted to try updating imgui-wgpu to use winit 0.30, but that would also mean updating everything related to it

**Comment by spearman** [comment]
> Never seen it fail on Linuxes.

Fails for me on Linux (NixOS 24.05)

```
     Running tests/atomic_counter.rs (target/debug/deps/atomic_counter-0c5734eca2025ef9)

running 1 test
test basic ... FAILED

failures:

---- basic stdout ----
thread 'basic' panicked at src/buffer/alloc.rs:1528:5:
Indexed buffer out of range
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d7f6ebacee13b6c03623c4b74197280454ede8de/library/std/src/panicking.rs:658:5
   1: core::panicking::panic_fmt
             at /rustc/d7f6ebacee13b6c03623c4b74197280454ede8de/library/core/src/panicking.rs:74:14
   2: glium::buffer::alloc::indexed_bind_buffer
             at ./src/buffer/alloc.rs:1493:21
   3: glium::buffer::alloc::Alloc::indexed_bind
             at ./src/buffer/alloc.rs:418:18
   4: glium::buffer::alloc::Alloc::prepare_and_bind_for_atomic_counter
             at ./src/buffer/alloc.rs:376:9
   5: <glium::buffer::view::BufferAnySlice as glium::BufferExt>::prepare_and_bind_for_atomic_counter
             at ./src/buffer/view.rs:1415:9
   6: glium::uniforms::bind::bind_atomic_counter
             at ./src/uniforms/bind.rs:282:13
   7: glium::uniforms::bind::<impl glium::UniformsExt for U>::bind_uniforms::{{closure}}
             at ./src/uniforms/bind.rs:111:35
   8: <glium::uniforms::uniforms::UniformsStorage<T,R> as glium::uniforms::Uniforms>::visit_values
             at ./src/uniforms/uniforms.rs:54:9
   9: glium::uniforms::bind::<impl glium::UniformsExt for U>::bind_uniforms
             at ./src/uniforms/bind.rs:55:9
  10: glium::ops::draw::draw
             at ./src/ops/draw.rs:170:5
  11: <glium::framebuffer::SimpleFrameBuffer as glium::Surface>::draw
             at ./src/framebuffer/mod.rs:320:9
  12: atomic_counter::basic
             at ./tests/atomic_counter.rs:57:5
  13: atomic_counter::basic::{{closure}}
             at ./tests/atomic_counter.rs:9:11
  14: core::ops::function::FnOnce::call_once
             at /rustc/d7f6ebacee13b6c03623c4b74197280454ede8de/library/core/src/ops/function.rs:250:5
  15: core::ops::function::FnOnce::call_once
             at /rustc/d7f6ebacee13b6c03623c4b74197280454ede8de/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    basic

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.45s

error: test failed, to rerun pass `--test atomic_counter`
```

**Comment by justincredible** [comment]
I've only had it fail on Windows, but this fixes it for me:

[`tests/atomic_counter.rs`](https://github.com/glium/glium/blob/4832c5606a09b5a0238b5c8292cb4d8791588900/tests/atomic_counter.rs)
``` diff
@@ -29,7 +29,7 @@ fn basic() {
-            layout(binding = 1) uniform atomic_uint counter;
+            uniform atomic_uint counter;
```

**Comment by justincredible** [comment]
I would have mentioned this at the beginning, but I forgot it existed.

When running the tests glium will look for an environment variable [`GLIUM_GL_VERSION`](https://github.com/glium/glium/blob/master/tests/support/mod.rs#L233) and attempt to parse its value. If it can, then it will try to use that version to run the tests.

``` sh
$ GLIUM_GL_VERSION=OpenGL\ 4.2 cargo test
```

This is only checked by the tests, so it won't have any effect on the info example.
